services:
  azubigo-email-tool:
    build:
      context: .
      dockerfile: Dockerfile
    image: darkcompiler/azubigoemailtool:latest
    container_name: azubigo-email-tool
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    labels:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
